# These are supported funding model platforms

Raphzee: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
codex: # Replace with a single Patreon username
codex: # Replace with a single Open Collective username
Raph_zee: # Replace with a single Ko-fi username
codex/babel: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
Restaurant-website: # Replace with a single Community Bridge project-name e.g., cloud-foundry
Zirra: # Replace with a single Liberapay username
Zirra: # Replace with a single IssueHunt username
Restaurant-website: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
Zirra: # Replace with a single Polar username
buy_codex_a_coffee: # Replace with a single Buy Me a Coffee username
Zirra.dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
